services:
  web:
    build:
      context: .
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - '8000:8000'
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 &
             celery -A app worker --loglevel=info"
    environment:
      - DB_HOST=db
      - DB_NAME=dbtest
      - DB_USER=devuser
      - DB_PASSWORD=devuser
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.5-alpine3.21
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devuser

  redis:
    image: redis:8.0.1-alpine
    ports:
      - '6379:6379'

volumes:
  dev-db-data:
