# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: candidate.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'candidate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61ndidate.proto\x12\tcandidate\" \n\x12\x43\x61ndidateIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"@\n\x17\x43\x61ndidateStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rscreening_log\x18\x02 \x01(\t2q\n\x16\x43\x61ndidateStatusService\x12W\n\x12GetCandidateStatus\x12\x1d.candidate.CandidateIdRequest\x1a\".candidate.CandidateStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'candidate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDIDATEIDREQUEST']._serialized_start=30
  _globals['_CANDIDATEIDREQUEST']._serialized_end=62
  _globals['_CANDIDATESTATUSRESPONSE']._serialized_start=64
  _globals['_CANDIDATESTATUSRESPONSE']._serialized_end=128
  _globals['_CANDIDATESTATUSSERVICE']._serialized_start=130
  _globals['_CANDIDATESTATUSSERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
